const API_URL = 'https://fsofkracsdlpuhnoslkn.supabase.co/rest/v1/leaderboard_students';
const API_KEY = 'sb_publishable_MKybnn3A0Vb9AQQXaHWjvg_zYWh3DQg';
let cachedPlayers = [];
const headers = { apikey: API_KEY, Authorization: `Bearer ${API_KEY}`, 'Content-Type': 'application/json' };
const ranked = () => [...cachedPlayers].sort((a, b) => b.points - a.points || a.name.localeCompare(b.name));
const crown = rank => rank < 4 ? `<span class="crown crown-${rank}" aria-label="${['gold', 'silver', 'bronze'][rank - 1]} place">♛</span>` : '';
async function fetchPlayers() { const r = await fetch(`${API_URL}?select=id,name,points&order=points.desc,name.asc`, { headers }); if (!r.ok) throw new Error('Could not load the leaderboard'); cachedPlayers = await r.json(); }
async function createPlayer(name, points) { const r = await fetch(API_URL, { method: 'POST', headers: { ...headers, Prefer: 'return=representation' }, body: JSON.stringify({ name, points }) }); if (!r.ok) throw new Error('Could not add the student'); }
async function savePlayers(players) { await Promise.all(players.map(async p => { const r = await fetch(`${API_URL}?id=eq.${p.id}`, { method: 'PATCH', headers, body: JSON.stringify({ name: p.name, points: p.points, updated_at: new Date().toISOString() }) }); if (!r.ok) throw new Error('Could not publish the standings'); })); }
function header(admin) { return `<header><a class="brand" href="/"><span class="star">✦</span>Northstar League</a><a class="admin-link" href="${admin ? '/' : '/admin'}">${admin ? 'Public board' : 'Admin'}</a></header>`; }
function publicBoard() { const list = ranked().slice(0, 10).map((p, i) => `<li class="leader-row rank-${i + 1}"><span class="rank">${i + 1}</span>${crown(i + 1)}<span class="leader-name">${p.name}</span></li>`).join(''); document.title = 'Live Leaders · Northstar League'; document.querySelector('#app').innerHTML = `${header(false)}<section class="board-wrap"><h1>Live Leaders</h1><p class="live"><span></span>Updating live</p><ol class="board" aria-label="Live leaderboard">${list}</ol></section><footer>A brighter game together</footer>`; }
function adminPanel(message = '') { const rows = ranked().map((p, i) => `<tr><td class="rank-cell">${i + 1}</td><td><label class="sr-only" for="name-${p.id}">Name for ${p.name}</label><input class="name-input" id="name-${p.id}" type="text" value="${p.name.replace(/&/g, '&amp;').replace(/"/g, '&quot;')}" data-name-id="${p.id}"></td><td><label class="sr-only" for="points-${p.id}">Points for ${p.name}</label><input id="points-${p.id}" type="number" min="0" step="1" value="${p.points}" data-id="${p.id}"></td></tr>`).join(''); document.title = 'Admin · Northstar League'; document.querySelector('#app').innerHTML = `${header(true)}<section class="admin-wrap"><div class="admin-intro"><h1>Update points</h1><p>Add students and update names or points. The public board shows the top 10 names and ranks only.</p></div><form id="points-form"><table><thead><tr><th>Rank</th><th>Student</th><th>Points</th></tr></thead><tbody>${rows}</tbody></table><div class="new-student"><label><span>Student name</span><input id="new-name" type="text" placeholder="e.g. Priya Shah" autocomplete="off"></label><label><span>Starting points</span><input id="new-points" type="number" min="0" step="1" value="0"></label><button class="add-student" type="button" id="add-student">Add student</button></div><div class="actions"><span id="saved" role="status">${message}</span><button type="submit">Publish standings</button></div></form><p class="admin-note">Changes are shared live across every device using the site.</p></section>`; document.querySelector('#add-student').addEventListener('click', async () => { const name = document.querySelector('#new-name').value.trim(); if (!name) return document.querySelector('#new-name').focus(); try { await createPlayer(name, Math.max(0, Number(document.querySelector('#new-points').value) || 0)); await hydrate(); } catch (e) { adminPanel(e.message); } }); document.querySelector('#points-form').addEventListener('submit', async e => { e.preventDefault(); const changes = cachedPlayers.map(p => ({ id: p.id, name: document.querySelector(`[data-name-id="${p.id}"]`).value.trim() || p.name, points: Math.max(0, Number(document.querySelector(`[data-id="${p.id}"]`).value) || 0) })); try { await savePlayers(changes); await hydrate('Published just now'); } catch (err) { adminPanel(err.message); } }); }
async function hydrate(message = '') { try { await fetchPlayers(); location.pathname === '/admin' ? adminPanel(message) : publicBoard(); } catch (e) { document.querySelector('#app').innerHTML = `<p class="load-error">${e.message}. Refresh to try again.</p>`; } }
hydrate(); if (location.pathname !== '/admin') setInterval(hydrate, 8000);
